# Generated by Django 5.1.2 on 2024-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_postagens_data_criacao_alter_postagens_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagens",
            name="data_publicacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
